"""Generate viewer.html: a self-contained card / deck / stats / replay browser.

Embeds the card database (from EN_Card_Data.csv via cards.py), the deck store
(registry/decks.json), and the replay stats (registry/replays.json) into one HTML file with
a sidebar UI. Card art is referenced by relative path to data/external/official/card_images/,
so the file must be opened from the repo (open pokemon-tcg-ai-battle/viewer.html directly).

Re-run after changing decks or downloading replays:
    python tools/build_stats.py && python tools/build_decks.py && python tools/build_viewer.py
"""
from __future__ import annotations

import json
from pathlib import Path

import cards  # tools/cards.py

ROOT = Path(__file__).resolve().parent.parent
DECKS = ROOT / "registry" / "decks.json"
REPLAYS = ROOT / "registry" / "replays.json"
MANIFEST = ROOT / "data" / "external" / "official" / "card_images" / "manifest.json"
OUT = ROOT / "viewer.html"
IMG_REL = "data/external/official/card_images"


def build_card_data() -> dict:
    have_img = set()
    if MANIFEST.exists():
        have_img = {int(k) for k in json.loads(MANIFEST.read_text(encoding="utf-8")).keys()}
    out = {}
    for cid, c in cards._load().items():
        out[cid] = {
            "n": c["name"], "hp": c.get("hp", ""), "ty": c.get("type", ""),
            "cat": c.get("category", ""), "st": c.get("stage", ""),
            "wk": c.get("weakness", ""), "rs": c.get("resistance", ""),
            "rt": c.get("retreat", ""), "exp": c.get("expansion", ""),
            "ev": c.get("prev_stage", ""),
            "a": [{"n": a["name"], "c": a["cost"], "d": a["damage"], "e": a["effect"]}
                  for a in c.get("attacks", [])],
            "img": cid in have_img,
        }
    return out


HTML = r"""<!doctype html>
<!-- GENERATED by tools/build_viewer.py. Do not edit; edit the data and re-run. -->
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>PTCG cabt viewer</title>
<style>
:root{
  --bg:#10151c; --panel:#161d27; --ink:#eef2f7; --soft:#94a3b8; --line:rgba(255,255,255,.08);
  --accent:#5e7fff; --good:#5fd38c; --bad:#ff6b6b; --warn:#ffce5a; --chip:#1f2937;
  --G:#4caf50; --R:#ef5350; --W:#42a5f5; --L:#ffd54f; --P:#ab47bc; --F:#a1887f;
  --D:#546e7a; --M:#90a4ae; --N:#d4af37; --C:#cbd5e1;
}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);font:14px/1.5 Inter,-apple-system,Segoe UI,Roboto,sans-serif}
a{color:var(--accent)}
.app{display:grid;grid-template-columns:208px 1fr;min-height:100vh}
nav{background:var(--panel);border-right:1px solid var(--line);position:sticky;top:0;height:100vh;
  padding:18px 12px;display:flex;flex-direction:column;gap:4px;overflow:auto}
.brand{font-weight:800;font-size:1.05rem;letter-spacing:-.01em;margin:0 6px 4px}
.brand small{display:block;color:var(--soft);font-weight:600;font-size:.66rem;text-transform:uppercase;letter-spacing:.1em}
.navlink{display:flex;align-items:center;gap:8px;padding:9px 12px;border-radius:8px;color:var(--ink);
  cursor:pointer;border-left:3px solid transparent;font-weight:600;user-select:none}
.navlink:hover{background:rgba(255,255,255,.04)}
.navlink.on{background:rgba(94,127,255,.14);border-left-color:var(--accent);color:#dbe5ff}
.navlink .c{margin-left:auto;color:var(--soft);font-size:.78rem;font-weight:700}
.sub{margin:2px 0 10px}
.sub .navlink{padding:6px 12px;font-weight:500;font-size:.88rem}
main{padding:22px 26px;min-width:0}
h1{font-size:1.5rem;margin:0 0 2px}
.muted{color:var(--soft)}
.bar{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin:14px 0}
input[type=search],select{background:var(--chip);border:1px solid var(--line);color:var(--ink);
  border-radius:8px;padding:8px 11px;font:inherit;min-width:180px}
input:focus,select:focus{outline:none;border-color:var(--accent)}
.chip{padding:5px 11px;border-radius:999px;background:var(--chip);border:1px solid var(--line);
  cursor:pointer;font-size:.8rem;font-weight:600;user-select:none}
.chip.on{background:var(--accent);border-color:var(--accent);color:#06122e}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(118px,1fr));gap:12px;margin-top:6px}
.card{background:var(--panel);border:1px solid var(--line);border-radius:10px;overflow:hidden;
  cursor:pointer;transition:transform .08s,border-color .08s}
.card:hover{transform:translateY(-2px);border-color:var(--accent)}
.card img{width:100%;display:block;aspect-ratio:451/630;object-fit:cover;background:#0b0f14}
.card .ph{width:100%;aspect-ratio:451/630;display:flex;align-items:center;justify-content:center;
  color:var(--soft);font-size:.7rem;text-align:center;padding:6px;background:#0b0f14}
.card .cap{padding:6px 8px;font-size:.72rem;line-height:1.25}
.card .cap b{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.dot{display:inline-block;width:11px;height:11px;border-radius:50%;vertical-align:-1px;margin-right:2px}
.pill{display:inline-block;font-size:.66rem;font-weight:800;text-transform:uppercase;letter-spacing:.03em;
  padding:2px 8px;border-radius:999px;background:var(--chip)}
.pill.ex{background:rgba(255,206,90,.18);color:var(--warn)}
.pill.mega{background:rgba(255,107,107,.18);color:var(--bad)}
/* detail panel */
#detail{position:fixed;top:0;right:0;width:360px;max-width:90vw;height:100vh;background:var(--panel);
  border-left:1px solid var(--line);box-shadow:-20px 0 40px rgba(0,0,0,.4);padding:18px 20px;overflow:auto;
  transform:translateX(110%);transition:transform .16s;z-index:20}
#detail.open{transform:none}
#detail img{width:60%;border-radius:8px;display:block;margin:6px auto 12px}
#detail h2{margin:.2rem 0}
#detail .close{position:absolute;top:12px;right:14px;cursor:pointer;color:var(--soft);font-size:1.3rem}
.kv{display:flex;gap:8px;flex-wrap:wrap;margin:8px 0}
.kv span{background:var(--chip);border:1px solid var(--line);border-radius:7px;padding:3px 9px;font-size:.78rem}
.atk{border-top:1px solid var(--line);padding:10px 0}
.atk .nm{font-weight:700}
.atk .dmg{float:right;color:var(--warn);font-weight:800}
.atk .ef{color:var(--soft);font-size:.82rem;margin-top:3px}
.cost{display:inline-flex;gap:2px;margin-right:6px}
/* decks */
.deckhead{display:flex;align-items:baseline;gap:12px;flex-wrap:wrap}
.statrow{display:flex;gap:10px;flex-wrap:wrap;margin:12px 0}
.stat{background:var(--panel);border:1px solid var(--line);border-radius:9px;padding:8px 13px;min-width:84px}
.stat b{display:block;font-size:1.35rem;line-height:1.1}
.stat small{color:var(--soft);text-transform:uppercase;font-size:.66rem;letter-spacing:.05em}
.sec{font-weight:800;margin:16px 0 6px;color:var(--soft);text-transform:uppercase;font-size:.72rem;letter-spacing:.08em}
.cnt{position:absolute;top:5px;left:5px;background:rgba(0,0,0,.78);border-radius:6px;padding:1px 7px;font-weight:800;font-size:.78rem}
.card{position:relative}
table{border-collapse:collapse;width:100%;margin-top:8px}
th,td{text-align:left;padding:7px 10px;border-bottom:1px solid var(--line);font-size:.86rem}
th{color:var(--soft);text-transform:uppercase;font-size:.7rem;letter-spacing:.06em}
tr:hover td{background:rgba(255,255,255,.02)}
.btn{background:var(--accent);color:#06122e;border:none;border-radius:8px;padding:8px 14px;font-weight:700;cursor:pointer}
.note{background:rgba(255,206,90,.08);border:1px solid rgba(255,206,90,.25);border-radius:9px;padding:10px 13px;color:#f0e4c0;font-size:.85rem;margin:10px 0}
.win{color:var(--good);font-weight:700}.loss{color:var(--bad);font-weight:700}
</style></head><body>
<div class="app">
  <nav>
    <div class="brand">PTCG<small>cabt viewer</small></div>
    <div class="navlink on" data-v="cards">Cards <span class="c" id="nc"></span></div>
    <div class="navlink" data-v="decks">Decks <span class="c" id="nd"></span></div>
    <div class="navlink" data-v="stats">Stats</div>
    <div class="navlink" data-v="replays">Replays <span class="c" id="nr"></span></div>
    <div id="decknav" class="sub"></div>
  </nav>
  <main id="main"></main>
</div>
<div id="detail"><span class="close" onclick="closeDetail()">&times;</span><div id="detailbody"></div></div>
<script>
const CARDS = __CARDS__;
const DECKS = __DECKS__;
const REPLAYS = __REPLAYS__;
const IMG = "__IMG__";
const ECOL = {G:'--G',R:'--R',W:'--W',L:'--L',P:'--P',F:'--F',D:'--D',M:'--M',N:'--N',C:'--C'};
function ecolor(l){return getComputedStyle(document.documentElement).getPropertyValue(ECOL[l]||'--C')||'#ccc'}
function energies(s){return (s.match(/\{(.)\}/g)||[]).map(x=>x[1])}
function dots(s){return energies(s).map(l=>`<span class="dot" style="background:${ecolor(l)}"></span>`).join('')}
function imgTag(id,cls){const c=CARDS[id]; return c&&c.img?`<img loading="lazy" src="${IMG}/${id}.jpg" alt="">`:`<div class="ph">${c?c.n:id}</div>`}
function isMega(c){return /mega/i.test(c.n)&&/ex/i.test(c.n)} function isEx(c){return /\bex\b/i.test(c.n)}
function catOf(c){const s=(c.cat||'')+(c.st||''); if(/energy/i.test(s))return 'Energy'; if(/pok/i.test(s)||c.hp&&/\d/.test(c.hp))return 'Pokemon'; return 'Trainer'}

let view='cards', q='', filt={cat:'',ty:'',ex:false}, deck=DECKS[0]&&DECKS[0].id;
const main=document.getElementById('main'), dnav=document.getElementById('decknav');
document.getElementById('nc').textContent=Object.keys(CARDS).length;
document.getElementById('nd').textContent=DECKS.length;
document.getElementById('nr').textContent=REPLAYS.length;

document.querySelectorAll('nav .navlink[data-v]').forEach(el=>el.onclick=()=>{
  view=el.dataset.v; document.querySelectorAll('nav .navlink').forEach(n=>n.classList.toggle('on',n===el));
  render();
});
function setView(v){view=v;document.querySelectorAll('nav .navlink[data-v]').forEach(n=>n.classList.toggle('on',n.dataset.v===v));render();}

function render(){ dnav.innerHTML=''; if(view==='cards')renderCards(); else if(view==='decks')renderDecks();
  else if(view==='stats')renderStats(); else renderReplays(); }

/* ---- cards ---- */
function cardMatch(id){const c=CARDS[id]; if(!c)return false;
  if(filt.cat&&catOf(c)!==filt.cat)return false;
  if(filt.ex&&!isEx(c))return false;
  if(filt.ty&&!energies(c.ty).includes(filt.ty)&&!(c.ty||'').includes(filt.ty))return false;
  if(q){const t=(c.n+' '+c.a.map(a=>a.n+' '+a.e).join(' ')).toLowerCase(); if(!t.includes(q))return false;}
  return true;}
function renderCards(){
  const types=['G','R','W','L','P','F','D','M','N','C'];
  main.innerHTML=`<h1>Cards</h1><div class="muted">${Object.keys(CARDS).length} cards in the cabt pool. Click a card for details.</div>
  <div class="bar"><input type="search" id="q" placeholder="search name or attack text" value="${q}">
  ${['Pokemon','Trainer','Energy'].map(c=>`<span class="chip ${filt.cat===c?'on':''}" data-cat="${c}">${c}</span>`).join('')}
  <span class="chip ${filt.ex?'on':''}" data-ex>ex / Mega</span>
  ${types.map(t=>`<span class="chip ${filt.ty===t?'on':''}" data-ty="${t}" title="${t}"><span class="dot" style="background:${ecolor(t)}"></span></span>`).join('')}
  </div><div class="grid" id="grid"></div>`;
  const ids=Object.keys(CARDS).map(Number).filter(cardMatch).slice(0,1400);
  document.getElementById('grid').innerHTML=ids.map(id=>{const c=CARDS[id];
    return `<div class="card" onclick="showCard(${id})">${imgTag(id)}<div class="cap"><b>${c.n}</b><span class="muted">${c.hp&&/\d/.test(c.hp)?c.hp+' HP':catOf(c)}</span></div></div>`}).join('')
    ||'<div class="muted">no matches</div>';
  document.getElementById('q').oninput=e=>{q=e.target.value.toLowerCase();renderCards();document.getElementById('q').focus();};
  main.querySelectorAll('[data-cat]').forEach(el=>el.onclick=()=>{filt.cat=filt.cat===el.dataset.cat?'':el.dataset.cat;renderCards()});
  main.querySelectorAll('[data-ty]').forEach(el=>el.onclick=()=>{filt.ty=filt.ty===el.dataset.ty?'':el.dataset.ty;renderCards()});
  main.querySelector('[data-ex]').onclick=()=>{filt.ex=!filt.ex;renderCards()};
}
function showCard(id){const c=CARDS[id]; const tag=isMega(c)?'<span class="pill mega">Mega ex - 3 prizes</span>':isEx(c)?'<span class="pill ex">ex - 2 prizes</span>':'';
  document.getElementById('detailbody').innerHTML=`${imgTag(id)}<h2>${c.n}</h2><div class="muted">${catOf(c)} ${c.st?'- '+c.st:''} ${c.exp?'- '+c.exp:''}</div>${tag}
  <div class="kv">${c.hp&&/\d/.test(c.hp)?`<span>HP ${c.hp}</span>`:''}${c.ty?`<span>${dots(c.ty)||c.ty} type</span>`:''}
  ${c.wk&&c.wk!=='n/a'?`<span>weak ${c.wk}</span>`:''}${c.rs&&c.rs!=='n/a'?`<span>resist ${c.rs}</span>`:''}
  ${c.rt&&/\d/.test(c.rt)?`<span>retreat ${c.rt}</span>`:''}${c.ev?`<span>from ${c.ev}</span>`:''}</div>
  ${c.a.map(a=>`<div class="atk"><span class="dmg">${a.d||''}</span><span class="nm"><span class="cost">${dots(a.c)}</span>${a.n}</span>${a.e?`<div class="ef">${a.e}</div>`:''}</div>`).join('')}
  <div class="atk muted" style="font-size:.78rem">card id ${id}</div>`;
  document.getElementById('detail').classList.add('open');}
function closeDetail(){document.getElementById('detail').classList.remove('open')}

/* ---- decks ---- */
function deckStats(ids){const cnt={Pokemon:0,Trainer:0,Energy:0},ty={}; let ex=0;
  ids.forEach(id=>{const c=CARDS[id]; if(!c)return; cnt[catOf(c)]++; if(isMega(c))ex+=3; else if(isEx(c))ex+=2;
    energies(c.ty).forEach(l=>ty[l]=(ty[l]||0)+1);}); return {cnt,ty,ex};}
function renderDecks(){
  dnav.innerHTML=DECKS.map(d=>`<div class="navlink ${d.id===deck?'on':''}" onclick="deck='${d.id}';render()">${d.name}</div>`).join('');
  const d=DECKS.find(x=>x.id===deck)||DECKS[0]; if(!d){main.innerHTML='<h1>Decks</h1><div class="muted">No decks yet. Build with tools/build_decks.py.</div>';return;}
  const ids=d.cards, c=new Map(); ids.forEach(i=>c.set(i,(c.get(i)||0)+1));
  const s=deckStats(ids);
  const groups={Pokemon:[],Trainer:[],Energy:[]}; [...c.keys()].forEach(i=>{const cc=CARDS[i]; if(cc)groups[catOf(cc)].push(i)});
  const tybadges=Object.entries(s.ty).sort((a,b)=>b[1]-a[1]).map(([l,n])=>`<span class="dot" style="background:${ecolor(l)}"></span>${n}`).join(' &nbsp;');
  main.innerHTML=`<div class="deckhead"><h1>${d.name}</h1><span class="pill">${d.source}</span></div>
  <div class="muted">${d.notes||'60-card deck. Names are auto-assigned; rename in registry/decks.json.'}</div>
  <div class="statrow"><div class="stat"><b>${s.cnt.Pokemon}</b><small>Pokemon</small></div><div class="stat"><b>${s.cnt.Trainer}</b><small>Trainer</small></div>
  <div class="stat"><b>${s.cnt.Energy}</b><small>Energy</small></div><div class="stat"><b>${s.ex}</b><small>prizes given on KO</small></div>
  <div class="stat" style="min-width:160px"><b style="font-size:.95rem">${tybadges||'-'}</b><small>energy types</small></div></div>
  <button class="btn" onclick="exportDeck('${d.id}')">Export deck.csv</button>
  ${['Pokemon','Trainer','Energy'].map(g=>groups[g].length?`<div class="sec">${g} (${s.cnt[g]})</div>
    <div class="grid">${groups[g].sort((a,b)=>c.get(b)-c.get(a)).map(i=>`<div class="card" onclick="showCard(${i})"><span class="cnt">${c.get(i)}x</span>${imgTag(i)}<div class="cap"><b>${CARDS[i]?CARDS[i].n:i}</b></div></div>`).join('')}</div>`:'').join('')}`;
}
function exportDeck(id){const d=DECKS.find(x=>x.id===id); const blob=new Blob([d.cards.join('\n')],{type:'text/csv'});
  const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=d.name.replace(/[^a-z0-9]+/gi,'_')+'_deck.csv'; a.click();}

/* ---- stats ---- */
function deckLabel(ids){ if(!ids||!ids.length)return '?'; let best=null;
  ids.forEach(id=>{const c=CARDS[id]; if(!c||!/\d/.test(c.hp||''))return; const hp=+c.hp||0; const k=(/ex/i.test(c.n)?1e4:0)+hp; if(!best||k>best[0])best=[k,c.n]}); return best?best[1]:'deck';}
function renderStats(){
  const real=REPLAYS.filter(r=>!r.self_play).length;
  const play={};
  REPLAYS.forEach(r=>{[r.played0,r.played1].forEach(p=>Object.entries(p||{}).forEach(([id,n])=>play[id]=(play[id]||0)+n))});
  const top=Object.entries(play).sort((a,b)=>b[1]-a[1]).slice(0,40);
  main.innerHTML=`<h1>Stats</h1><div class="muted">Aggregated from parsed replays in data/external/replays/.</div>
  <div class="note">${REPLAYS.length} replay(s) parsed, ${real} real opponent match(es). Stats are thin until real ranked-match replays are downloaded. Drop more replays into data/external/replays/ and run tools/build_stats.py then tools/build_viewer.py.</div>
  <div class="statrow"><div class="stat"><b>${REPLAYS.length}</b><small>replays</small></div><div class="stat"><b>${real}</b><small>real matches</small></div>
  <div class="stat"><b>${Object.keys(play).length}</b><small>distinct cards played</small></div></div>
  <div class="sec">Most-played cards (across replays)</div>
  <table><tr><th>card</th><th>type</th><th>times played</th></tr>
  ${top.map(([id,n])=>`<tr><td><a onclick="showCard(${id})">${CARDS[id]?CARDS[id].n:id}</a></td><td>${CARDS[id]?catOf(CARDS[id]):''}</td><td>${n}</td></tr>`).join('')||'<tr><td colspan=3 class="muted">none yet</td></tr>'}</table>`;
}
/* ---- replays ---- */
function renderReplays(){
  main.innerHTML=`<h1>Replays</h1><div class="muted">Parsed cabt episodes. Self-play = your validation games; real matches show the opponent's deck.</div>
  <table><tr><th>id</th><th>player 0 deck</th><th>player 1 deck</th><th>result</th><th>steps</th><th>type</th></tr>
  ${REPLAYS.map(r=>`<tr><td>${(r.id||'').slice(0,10)}</td><td>${deckLabel(r.deck0)}</td><td>${deckLabel(r.deck1)}</td>
    <td>${r.winner===null?'draw':'<span class="'+(r.winner===0?'win':'loss')+'">P'+r.winner+' won</span>'}</td>
    <td>${r.steps}</td><td>${r.self_play?'<span class="muted">self-play</span>':'real'}</td></tr>`).join('')
    ||'<tr><td colspan=6 class="muted">no replays yet</td></tr>'}</table>`;
}
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDetail()});
render();
</script></body></html>"""


def main() -> None:
    cd = build_card_data()
    decks = json.loads(DECKS.read_text(encoding="utf-8")) if DECKS.exists() else []
    replays = json.loads(REPLAYS.read_text(encoding="utf-8")) if REPLAYS.exists() else []
    html = (HTML
            .replace("__CARDS__", json.dumps(cd, ensure_ascii=False, separators=(",", ":")))
            .replace("__DECKS__", json.dumps(decks, ensure_ascii=False, separators=(",", ":")))
            .replace("__REPLAYS__", json.dumps(replays, ensure_ascii=False, separators=(",", ":")))
            .replace("__IMG__", IMG_REL))
    OUT.write_text(html, encoding="utf-8")
    kb = len(html.encode("utf-8")) // 1024
    print(f"wrote {OUT.relative_to(ROOT)} ({kb} KB, {len(cd)} cards, {len(decks)} decks, {len(replays)} replays)")


if __name__ == "__main__":
    main()
