"""Manage the deck store (registry/decks.json): list, show, clone, rename, remove, import.

Auto-collected decks have ids like D001 (regenerated by build_decks.py). Your own decks get
ids like U001 and source "user" and are preserved when build_decks.py re-runs. Clone an
existing deck to get an editable user copy, then edit its `cards` list in registry/decks.json
by hand, or re-import from a deck.csv. Re-run `python tools/build_viewer.py` to see changes
in viewer.html.

    python tools/decks.py list
    python tools/decks.py show D003
    python tools/decks.py clone D003 --name "Lucario test v1"
    python tools/decks.py rename U001 "Lucario aggro"
    python tools/decks.py import "My Deck" path/to/deck.csv
    python tools/decks.py remove U001
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import cards

ROOT = Path(__file__).resolve().parent.parent
STORE = ROOT / "registry" / "decks.json"


def load() -> list[dict]:
    return json.loads(STORE.read_text(encoding="utf-8")) if STORE.exists() else []


def save(decks: list[dict]) -> None:
    STORE.write_text(json.dumps(decks, indent=2), encoding="utf-8")


def next_user_id(decks: list[dict]) -> str:
    nums = [int(d["id"][1:]) for d in decks if d.get("id", "").startswith("U") and d["id"][1:].isdigit()]
    return f"U{(max(nums) + 1) if nums else 1:03d}"


def find(decks: list[dict], did: str) -> dict | None:
    return next((d for d in decks if d.get("id") == did), None)


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)
    sub.add_parser("list")
    s = sub.add_parser("show"); s.add_argument("id")
    c = sub.add_parser("clone"); c.add_argument("id"); c.add_argument("--name", default=None)
    r = sub.add_parser("rename"); r.add_argument("id"); r.add_argument("name")
    rm = sub.add_parser("remove"); rm.add_argument("id")
    im = sub.add_parser("import"); im.add_argument("name"); im.add_argument("csv")
    args = p.parse_args()
    decks = load()

    if args.cmd == "list":
        for d in decks:
            print(f"  {d['id']}  {d['name']:42s}  {len(d.get('cards', []))} cards  ({d.get('source','')})")
    elif args.cmd == "show":
        d = find(decks, args.id)
        if not d:
            raise SystemExit(f"no deck {args.id}")
        print(f"{d['id']}  {d['name']}  ({d.get('source','')})")
        for n, cid, nm in cards.decode_deck(d["cards"]):
            print(f"  {n:2d}x [{cid}] {nm}")
    elif args.cmd == "clone":
        d = find(decks, args.id)
        if not d:
            raise SystemExit(f"no deck {args.id}")
        nid = next_user_id(decks)
        decks.append({"id": nid, "name": args.name or (d["name"] + " (copy)"),
                      "source": "user", "cards": list(d["cards"]), "notes": f"cloned from {d['id']}"})
        save(decks)
        print(f"cloned {args.id} -> {nid}. Edit its cards in registry/decks.json, then run build_viewer.py")
    elif args.cmd == "rename":
        d = find(decks, args.id)
        if not d:
            raise SystemExit(f"no deck {args.id}")
        d["name"] = args.name
        save(decks)
        print(f"renamed {args.id} -> {args.name}")
    elif args.cmd == "remove":
        if not find(decks, args.id):
            raise SystemExit(f"no deck {args.id}")
        save([d for d in decks if d["id"] != args.id])
        print(f"removed {args.id}")
    elif args.cmd == "import":
        ids = [int(x) for x in Path(args.csv).read_text().split() if x.strip()]
        nid = next_user_id(decks)
        decks.append({"id": nid, "name": args.name, "source": "user", "cards": ids, "notes": f"imported from {args.csv}"})
        save(decks)
        print(f"imported {len(ids)} cards as {nid} ({args.name})")


if __name__ == "__main__":
    main()
