"""Hypothesis + experiment + result registry for the Pokemon TCG AI Battle work.

Purpose (the one this exists to solve): stop the recurring failure where a model
reaches a conclusion, writes it into a prose doc, and a later model reads the
discredited conclusion and rehashes it. The fix is structural, not motivational:

  - The canon is append-only JSONL (hypotheses / experiments / results). One record
    per line. Clean git diffs, mergeable, human-readable. This is the source of truth.
  - A SQLite + FTS5 database is BUILT from the JSONL (it is a derived cache, git-ignored).
    Its only job is the search gate: before proposing or re-testing an idea you run
    `python registry.py search "<idea>"`. If a matching hypothesis is REFUTED, you see
    the falsifying evidence and the explicit RE-OPEN GATE. You may not retry a refuted
    hypothesis unless its gate condition has measurably changed.
  - The human-readable views BELIEFS.md and GRAVEYARD.md are GENERATED from the canon
    (banner at the top, "do not edit"). No one hand-maintains a beliefs doc, so stale
    prose can never be trusted by accident.

Lifecycle of a hypothesis:
    open -> supported | refuted | superseded | parked
  A status change must carry evidence. refuted/parked must carry a reopen_gate.

Stdlib only (sqlite3, json, argparse). Python 3.13. Modeled on the master-organizer
claims_store.py conventions (FTS5, CROSS JOIN query order, generated-views-from-store).
Run `python registry.py --help`.
"""
from __future__ import annotations

import argparse
import json
import re
import sqlite3
from datetime import date
from html import escape
from pathlib import Path
from typing import Any, Iterable

ROOT = Path(__file__).resolve().parent
HYP_JSONL = ROOT / "hypotheses.jsonl"
EXP_JSONL = ROOT / "experiments.jsonl"
RES_JSONL = ROOT / "results.jsonl"
DB_PATH = ROOT / "ground-truth" / "registry.db"
BELIEFS_MD = ROOT / "BELIEFS.md"
GRAVEYARD_MD = ROOT / "GRAVEYARD.md"

STATUSES = {"open", "supported", "refuted", "superseded", "parked"}
VERDICTS = {"supports", "refutes", "inconclusive"}
GENERATED_BANNER = (
    "<!-- GENERATED from the registry JSONL by `python registry.py render`. "
    "Do not edit this file. Edit the JSONL canon and re-render. -->"
)

# --------------------------------------------------------------------------- #
# JSONL canon (source of truth)
# --------------------------------------------------------------------------- #

def _read_jsonl(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    rows = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line:
            rows.append(json.loads(line))
    return rows


def _write_jsonl(path: Path, rows: Iterable[dict[str, Any]]) -> None:
    path.write_text(
        "".join(json.dumps(r, ensure_ascii=False, sort_keys=False) + "\n" for r in rows),
        encoding="utf-8",
    )


def _today() -> str:
    return date.today().isoformat()


def _next_id(rows: list[dict[str, Any]], prefix: str) -> str:
    nums = [int(m.group(1)) for r in rows if (m := re.match(rf"{prefix}(\d+)$", str(r.get("id", ""))))]
    return f"{prefix}{(max(nums) + 1) if nums else 1:03d}"


# --------------------------------------------------------------------------- #
# Mutations on the canon
# --------------------------------------------------------------------------- #

def add_hypothesis(
    *, title: str, statement: str, test: str = "", refute_condition: str = "",
    confidence: str = "medium", tags: list[str] | None = None,
) -> str:
    rows = _read_jsonl(HYP_JSONL)
    hid = _next_id(rows, "H")
    rows.append({
        "id": hid, "created": _today(), "updated": _today(),
        "title": title, "statement": statement, "test": test,
        "refute_condition": refute_condition, "status": "open",
        "confidence": confidence, "evidence": "", "reopen_gate": "",
        "superseded_by": "", "tags": tags or [], "links": [],
    })
    _write_jsonl(HYP_JSONL, rows)
    return hid


def set_status(
    hid: str, status: str, *, evidence: str, reopen_gate: str = "",
    superseded_by: str = "", confidence: str | None = None,
) -> None:
    if status not in STATUSES:
        raise SystemExit(f"status must be one of {sorted(STATUSES)}")
    if status in {"refuted", "parked"} and not reopen_gate:
        raise SystemExit(
            f"status '{status}' requires --gate: the measurable condition under which "
            "retrying this hypothesis is allowed again."
        )
    rows = _read_jsonl(HYP_JSONL)
    found = False
    for r in rows:
        if r.get("id") == hid:
            r["status"] = status
            r["evidence"] = evidence
            r["reopen_gate"] = reopen_gate
            r["superseded_by"] = superseded_by
            if confidence:
                r["confidence"] = confidence
            r["updated"] = _today()
            found = True
            break
    if not found:
        raise SystemExit(f"no hypothesis {hid}")
    _write_jsonl(HYP_JSONL, rows)


def add_experiment(*, hypothesis_id: str, description: str, config: str = "", code_ref: str = "") -> str:
    rows = _read_jsonl(EXP_JSONL)
    eid = _next_id(rows, "E")
    rows.append({
        "id": eid, "date": _today(), "hypothesis_id": hypothesis_id,
        "description": description, "config": config, "code_ref": code_ref,
        "status": "done",
    })
    _write_jsonl(EXP_JSONL, rows)
    return eid


def add_result(
    *, experiment_id: str, hypothesis_id: str, metric: str, value: float,
    baseline: float | None = None, n: int | None = None, verdict: str = "inconclusive",
    provenance: str = "", notes: str = "",
) -> str:
    if verdict not in VERDICTS:
        raise SystemExit(f"verdict must be one of {sorted(VERDICTS)}")
    rows = _read_jsonl(RES_JSONL)
    rid = _next_id(rows, "R")
    rows.append({
        "id": rid, "date": _today(), "experiment_id": experiment_id,
        "hypothesis_id": hypothesis_id, "metric": metric, "value": value,
        "baseline": baseline, "n": n, "verdict": verdict,
        "provenance": provenance, "notes": notes,
    })
    _write_jsonl(RES_JSONL, rows)
    return rid


# --------------------------------------------------------------------------- #
# Derived SQLite + FTS5 index (the search gate)
# --------------------------------------------------------------------------- #

_SCHEMA = """
CREATE TABLE hypotheses (
  id TEXT PRIMARY KEY, created TEXT, updated TEXT, title TEXT, statement TEXT,
  test TEXT, refute_condition TEXT, status TEXT, confidence TEXT, evidence TEXT,
  reopen_gate TEXT, superseded_by TEXT, tags TEXT, links TEXT
);
CREATE VIRTUAL TABLE hyp_fts USING fts5(
  title, statement, evidence, tags, content='hypotheses', content_rowid='rowid'
);
CREATE TABLE experiments (
  id TEXT PRIMARY KEY, date TEXT, hypothesis_id TEXT, description TEXT,
  config TEXT, code_ref TEXT, status TEXT
);
CREATE TABLE results (
  id TEXT PRIMARY KEY, date TEXT, experiment_id TEXT, hypothesis_id TEXT,
  metric TEXT, value REAL, baseline REAL, n INTEGER, verdict TEXT,
  provenance TEXT, notes TEXT
);
"""


def rebuild_db() -> Path:
    """Rebuild the derived SQLite index from the JSONL canon. The DB is disposable."""
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    if DB_PATH.exists():
        DB_PATH.unlink()
    conn = sqlite3.connect(str(DB_PATH))
    conn.executescript(_SCHEMA)
    for r in _read_jsonl(HYP_JSONL):
        conn.execute(
            "INSERT INTO hypotheses VALUES (:id,:created,:updated,:title,:statement,:test,"
            ":refute_condition,:status,:confidence,:evidence,:reopen_gate,:superseded_by,:tags,:links)",
            {**r, "tags": " ".join(r.get("tags", [])), "links": " ".join(r.get("links", []))},
        )
    conn.execute(
        "INSERT INTO hyp_fts(rowid, title, statement, evidence, tags) "
        "SELECT rowid, title, statement, evidence, tags FROM hypotheses"
    )
    for r in _read_jsonl(EXP_JSONL):
        conn.execute("INSERT INTO experiments VALUES (:id,:date,:hypothesis_id,:description,:config,:code_ref,:status)", r)
    for r in _read_jsonl(RES_JSONL):
        conn.execute("INSERT INTO results VALUES (:id,:date,:experiment_id,:hypothesis_id,:metric,:value,:baseline,:n,:verdict,:provenance,:notes)", r)
    conn.commit()
    conn.close()
    return DB_PATH


def _fts_query(text: str) -> str | None:
    terms = [t for t in re.findall(r"[\w']+", text) if t]
    if not terms:
        return None
    return " OR ".join('"' + t.replace('"', '""') + '"' for t in terms)


def search(query: str, limit: int = 20) -> list[dict[str, Any]]:
    """Full-text search hypotheses. This is the anti-rehash gate: run before proposing."""
    rebuild_db()
    match = _fts_query(query)
    if match is None:
        return []
    conn = sqlite3.connect(str(DB_PATH))
    conn.row_factory = sqlite3.Row
    rows = conn.execute(
        "SELECT h.id, h.title, h.statement, h.status, h.confidence, h.evidence, h.reopen_gate "
        "FROM hyp_fts CROSS JOIN hypotheses AS h ON h.rowid = hyp_fts.rowid "
        "WHERE hyp_fts MATCH ? ORDER BY bm25(hyp_fts) LIMIT ?",
        (match, limit),
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows]


# --------------------------------------------------------------------------- #
# Generated views (the reading layer)
# --------------------------------------------------------------------------- #

def _results_by_hyp() -> dict[str, list[dict[str, Any]]]:
    out: dict[str, list[dict[str, Any]]] = {}
    for r in _read_jsonl(RES_JSONL):
        out.setdefault(r.get("hypothesis_id", ""), []).append(r)
    return out


def _fmt_result(r: dict[str, Any]) -> str:
    base = f" vs {r['baseline']}" if r.get("baseline") is not None else ""
    n = f", n={r['n']}" if r.get("n") is not None else ""
    prov = f" [{r['provenance']}]" if r.get("provenance") else ""
    return f"{r.get('metric','')}={r.get('value','')}{base}{n} -> {r.get('verdict','')}{prov}"


def render() -> tuple[Path, Path]:
    hyps = _read_jsonl(HYP_JSONL)
    res = _results_by_hyp()

    def latest_result(hid: str) -> str:
        rs = res.get(hid, [])
        return _fmt_result(rs[-1]) if rs else ""

    live = [h for h in hyps if h.get("status") != "refuted" and not (h.get("status") == "superseded")]
    dead = [h for h in hyps if h.get("status") in {"refuted", "superseded"}]

    order = {"supported": 0, "open": 1, "parked": 2}
    live.sort(key=lambda h: (order.get(h.get("status", "open"), 3), h.get("id", "")))

    # BELIEFS.md
    b = [GENERATED_BANNER, "", "# Current beliefs", "",
         "Live hypotheses, generated from the registry. `supported` = a current working",
         "truth (still falsifiable). `open` = untested or in progress. `parked` = set aside",
         "with a re-open gate. Refuted and superseded hypotheses are in [GRAVEYARD.md](GRAVEYARD.md).",
         "", f"Counts: {len(hyps)} total, {len(live)} live, {len(dead)} in the graveyard.", ""]
    if any(h.get("status") == "supported" for h in live):
        b += ["## Supported (current working truths)", "",
              "| id | claim | confidence | evidence | latest result | updated |",
              "|---|---|---|---|---|---|"]
        for h in live:
            if h.get("status") == "supported":
                b.append(_row(h, latest_result(h["id"])))
        b.append("")
    b += ["## Open / parked", "",
          "| id | status | claim | confidence | how to test | latest result | updated |",
          "|---|---|---|---|---|---|---|"]
    for h in live:
        if h.get("status") != "supported":
            b.append(
                f"| {h['id']} | {h.get('status','')} | {_esc(h.get('statement',''))} "
                f"| {h.get('confidence','')} | {_esc(h.get('test',''))} "
                f"| {_esc(latest_result(h['id']))} | {h.get('updated','')} |"
            )
    b.append("")
    BELIEFS_MD.write_text("\n".join(b) + "\n", encoding="utf-8")

    # GRAVEYARD.md
    g = [GENERATED_BANNER, "", "# Graveyard (refuted and superseded)", "",
         "Do NOT re-propose or re-test anything here unless its **re-open gate** condition has",
         "measurably changed. This list exists specifically to stop rehashing discredited ideas.",
         "", "| id | status | claim | falsifying evidence | re-open gate | superseded by | updated |",
         "|---|---|---|---|---|---|---|"]
    for h in sorted(dead, key=lambda h: h.get("id", "")):
        g.append(
            f"| {h['id']} | {h.get('status','')} | {_esc(h.get('statement',''))} "
            f"| {_esc(h.get('evidence',''))} | {_esc(h.get('reopen_gate',''))} "
            f"| {h.get('superseded_by','')} | {h.get('updated','')} |"
        )
    if not dead:
        g.append("| | | nothing refuted yet | | | | |")
    g.append("")
    GRAVEYARD_MD.write_text("\n".join(g) + "\n", encoding="utf-8")
    return BELIEFS_MD, GRAVEYARD_MD


def _esc(s: Any) -> str:
    return str(s).replace("|", "\\|").replace("\n", " ")


def _row(h: dict[str, Any], latest: str) -> str:
    return (f"| {h['id']} | {_esc(h.get('statement',''))} | {h.get('confidence','')} "
            f"| {_esc(h.get('evidence',''))} | {_esc(latest)} | {h.get('updated','')} |")


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #

def _cli() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)

    a = sub.add_parser("add", help="add a hypothesis")
    a.add_argument("--title", required=True)
    a.add_argument("--statement", required=True, help="the falsifiable claim")
    a.add_argument("--test", default="", help="how it would be tested")
    a.add_argument("--refute", default="", help="what observation would refute it")
    a.add_argument("--confidence", default="medium", choices=["low", "medium", "high"])
    a.add_argument("--tags", default="", help="comma-separated")

    s = sub.add_parser("status", help="change a hypothesis status (carries evidence)")
    s.add_argument("id")
    s.add_argument("new", choices=sorted(STATUSES))
    s.add_argument("--evidence", required=True)
    s.add_argument("--gate", default="", help="re-open gate (required for refuted/parked)")
    s.add_argument("--superseded-by", default="")
    s.add_argument("--confidence", default=None, choices=["low", "medium", "high"])

    e = sub.add_parser("experiment", help="log an experiment against a hypothesis")
    e.add_argument("--hyp", required=True)
    e.add_argument("--desc", required=True)
    e.add_argument("--config", default="")
    e.add_argument("--code", default="")

    r = sub.add_parser("result", help="record a result for an experiment")
    r.add_argument("--exp", required=True)
    r.add_argument("--hyp", required=True)
    r.add_argument("--metric", required=True)
    r.add_argument("--value", required=True, type=float)
    r.add_argument("--baseline", default=None, type=float)
    r.add_argument("--n", default=None, type=int)
    r.add_argument("--verdict", default="inconclusive", choices=sorted(VERDICTS))
    r.add_argument("--provenance", default="", help="local-sim | kaggle-LB | manual")
    r.add_argument("--notes", default="")

    sr = sub.add_parser("search", help="search hypotheses (run BEFORE proposing an idea)")
    sr.add_argument("query")

    sub.add_parser("render", help="regenerate BELIEFS.md and GRAVEYARD.md")
    sub.add_parser("rebuild", help="rebuild the derived SQLite index from JSONL")
    sub.add_parser("list", help="list all hypotheses with status")

    args = p.parse_args()
    if args.cmd == "add":
        hid = add_hypothesis(
            title=args.title, statement=args.statement, test=args.test,
            refute_condition=args.refute, confidence=args.confidence,
            tags=[t.strip() for t in args.tags.split(",") if t.strip()],
        )
        render()
        print(f"added {hid}")
    elif args.cmd == "status":
        set_status(args.id, args.new, evidence=args.evidence, reopen_gate=args.gate,
                   superseded_by=args.superseded_by, confidence=args.confidence)
        render()
        print(f"{args.id} -> {args.new}")
    elif args.cmd == "experiment":
        print("added", add_experiment(hypothesis_id=args.hyp, description=args.desc, config=args.config, code_ref=args.code))
    elif args.cmd == "result":
        rid = add_result(experiment_id=args.exp, hypothesis_id=args.hyp, metric=args.metric,
                         value=args.value, baseline=args.baseline, n=args.n, verdict=args.verdict,
                         provenance=args.provenance, notes=args.notes)
        render()
        print(f"added {rid}")
    elif args.cmd == "search":
        hits = search(args.query)
        if not hits:
            print("no matching hypotheses. (clear to propose, but it may simply be unrecorded)")
        for h in hits:
            flag = "  <-- REFUTED, check the re-open gate" if h["status"] == "refuted" else ""
            print(f"[{h['id']}] {h['status'].upper()}{flag}: {h['title']}")
            print(f"      {h['statement']}")
            if h["status"] in {"refuted", "superseded", "parked"}:
                print(f"      evidence: {h['evidence']}")
                if h["reopen_gate"]:
                    print(f"      re-open gate: {h['reopen_gate']}")
    elif args.cmd == "render":
        b, g = render()
        print(f"wrote {b.name} and {g.name}")
    elif args.cmd == "rebuild":
        print(f"rebuilt {rebuild_db()}")
    elif args.cmd == "list":
        for h in _read_jsonl(HYP_JSONL):
            print(f"[{h['id']}] {h.get('status','').upper():11s} {h.get('title','')}")


if __name__ == "__main__":
    _cli()
